name: Build Executable
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      shell: bash
      run: go build -v ./...
    - name: Test
      shell: bash
      run: go test -v ./...
