name: Build Executable
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build exe
      shell: bash
      run: go build -v ./...
    - name: Run tests
      shell: bash
      run: go test -v ./...
    - name: Upload exe
      uses: actions/upload-artifact@v2.2.4
      with:
        name: cr1ck_t-bundle
        path: |
          cr1ck_t.exe
          assets/

